$OVITO_EXE_PATH="C:\Program Files\Ovito\ovito.exe"

# $OVITO_FILE_1="T:\COLOR_NANOMETRIC_CUTTING_ISOMETRIC_VIEW.ovito"
$OVITO_FILE_2="T:\COLOR_NANOMETRIC_CUTTING_ISOMETRIC_VIEW_GROOVE.ovito"
$OVITO_FILE_3="T:\COLOR_NANOMETRIC_CUTTING_X+_VIEW_GROOVE.ovito"

Start-Process -FilePath $OVITO_EXE_PATH -ArgumentList $OVITO_FILE_2
Start-Process -FilePath $OVITO_EXE_PATH -ArgumentList $OVITO_FILE_3
